# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Odigo.Chat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


	#BD
   	pod 'RealmSwift'

	#UI

	pod 'PageMenu'
	pod 'lottie-ios'

	
	#Crypto

	pod 'Sodium', '~> 0.3'
	pod 'BCryptSwift', '~> 0.1'

	#Network

	pod "SwiftDDP", "~> 0.4.1"
	pod 'SwiftyJSON', '~> 3.1'
	pod 'SDWebImage', '~>3.8'


  target 'Odigo.ChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Odigo.ChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
